dist: focal
language: python
python:
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10'
  - '3.11'
install:
  - pip install -r requirements.txt
script:
  - mypy typedconfig --strict
  - pytest --cov
  - codecov
deploy:
  provider: pypi
  username: __token__
  password:
    secure: MCRC94AUqj5+1roNAXpEcFUBPSVX7VIwTIj9fAeYyaiOVluiHtK4NqvjYnJj0IFd8j2niaoazA/lTlLtBo/Wdz9ARvVUx1XE8zAqf/qRAQgHSoVyc5QXszubrWS0YeMX3L7BE/f1BmEb2LKq3RHzSXZN1/NfWZbVAhLH/ET/IQrZZyxUhFhOoUEhivyQQfzqbia857W9iCAxu6DPlLnkEyoogh9rlaSAHcPxS30PL9oUsiW75pmR02yvppUMi3jKMkVMQ5/BXoO1hRcMkZmZTBNm6A7Ixhrp7WHH1AxqjoYMlz/8hhL8n1YdRPjRzCdlbIykIBBgNAh502ERryImQxLZfnBP+urnKzSmFCTqSFewzDT4ObIRA1IXe69wwvwKZLBU9c292jCwk4O4HnQPkvv6I5Rl4O2Ca4hEQoChH7UX7aMNxlE6F2SgQtuA44EgW0wKbjr7abGlzJHQKCM7AKOxTLhDFC6rihhHm/0ciscXDi+7EqIcTolev8sG1lGkoXgHT8OXpvaKj4VmSnDS7JpUe3jAjnnFkD3xCAZbQu0Iz6sjIlZWK9v2Bz7mdrv4c3wbrfZTCP+blpT8ZhvWOKWfv/CbFyiViKlsWFnuVbnE0I1ETgj1cT+bfvKNp4s09cYTUkN4y48cy3ffP/VOh/cYFT3+TWommBgf3hXDo3I=
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
